-- ---------------------------------------------------------------------------
-- FX trade lifecycle: baseline schema.
--
-- Shape notes:
--  * Money is numeric, never floating point. Amounts carry 2 decimal places,
--    FX rates 8 — USD/JPY quotes to 3 and EUR/USD to 5, and forward points add
--    precision below that, so 8 leaves headroom without pretending to more.
--  * trade_event is append-only. Nothing in the application updates or deletes
--    a row in it; the current status on `trade` is a cache of the last event.
--  * Every business identifier a human quotes (trade_ref, counterparty code,
--    pair symbol) is unique in the database, not just in application code.
--  * Currency codes are varchar(3), not char(3). char is tempting for a fixed
--    three-letter code, but PostgreSQL reports it as bpchar, which Hibernate's
--    schema validator refuses against a String field — and char's blank-padding
--    semantics are a trap in comparisons anyway.
--  * Timestamps are timestamptz. These columns hold instants — the moment a
--    trade was captured — and an instant without a time zone is ambiguous the
--    moment the service runs anywhere but one machine. Dates that are dates
--    (trade_date, value_date) stay plain `date`: a value date is 12 March, not
--    a moment.
-- ---------------------------------------------------------------------------

-- --- users -----------------------------------------------------------------

create table app_user
(
    id            bigint generated by default as identity primary key,
    username      varchar(120) not null,
    full_name     varchar(160) not null,
    password_hash varchar(120) not null,
    role          varchar(20)  not null,
    active        boolean      not null default true,
    constraint app_user_username_unique unique (username),
    constraint app_user_role_valid check (role in ('TRADER', 'MIDDLE_OFFICE', 'VIEWER'))
);

-- --- reference data --------------------------------------------------------

create table currency
(
    code        varchar(3)   primary key,
    name        varchar(60)  not null,
    minor_units smallint     not null default 2
);

create table currency_pair
(
    id            bigint generated by default as identity primary key,
    symbol        varchar(7) not null,
    base_ccy      varchar(3) not null references currency (code),
    quote_ccy     varchar(3) not null references currency (code),
    -- Business days between trade date and spot value date. Two for almost
    -- everything; one for USD/CAD, and some emerging-market pairs.
    spot_lag_days smallint   not null default 2,
    -- 10000 for a pair quoted to 4 decimals, 100 for a JPY pair. Used to turn
    -- a rate difference into forward points.
    pip_factor    integer    not null default 10000,
    rate_scale    smallint   not null default 5,
    active        boolean    not null default true,
    constraint currency_pair_symbol_unique unique (symbol),
    constraint currency_pair_distinct check (base_ccy <> quote_ccy)
);

create table counterparty
(
    id      bigint generated by default as identity primary key,
    code    varchar(12)  not null,
    name    varchar(160) not null,
    country varchar(2),
    -- Notional ceiling per trade, in the pair's base currency. Null = no limit.
    trade_limit numeric(20, 2),
    active  boolean      not null default true,
    constraint counterparty_code_unique unique (code)
);

create table holiday
(
    id            bigint generated by default as identity primary key,
    currency_code varchar(3)   not null references currency (code),
    holiday_date  date         not null,
    description   varchar(120) not null,
    constraint holiday_unique unique (currency_code, holiday_date)
);

-- --- market data -----------------------------------------------------------

create table fx_rate
(
    id         bigint generated by default as identity primary key,
    pair_id    bigint         not null references currency_pair (id),
    rate_date  date           not null,
    spot_mid   numeric(18, 8) not null,
    -- Annualised deposit rates for the two currencies, as decimals (0.0425 =
    -- 4.25%). Forward pricing needs both sides, not just the spot.
    base_rate  numeric(9, 6)  not null,
    quote_rate numeric(9, 6)  not null,
    source     varchar(40)    not null default 'DEMO',
    constraint fx_rate_unique unique (pair_id, rate_date),
    constraint fx_rate_positive check (spot_mid > 0)
);

create index fx_rate_pair_date_idx on fx_rate (pair_id, rate_date desc);

-- --- trades ----------------------------------------------------------------

-- Human-facing trade references come from a database sequence rather than a
-- counter in the application: two application instances must never mint the
-- same reference, and "FX-2026-001042" is what someone reads down a phone.
create sequence trade_ref_seq start with 1001 increment by 1;

create table trade
(
    id              bigint generated by default as identity primary key,
    trade_ref       varchar(20)    not null,
    -- Supplied by the caller. Unique, so replaying the same booking request
    -- cannot create a second trade.
    external_ref    varchar(60),
    pair_id         bigint         not null references currency_pair (id),
    counterparty_id bigint         not null references counterparty (id),
    product         varchar(10)    not null,
    direction       varchar(4)     not null,
    tenor           varchar(6),
    notional        numeric(20, 2) not null,
    rate            numeric(18, 8) not null,
    counter_amount  numeric(20, 2) not null,
    trade_date      date           not null,
    value_date      date           not null,
    book            varchar(30)    not null,
    status          varchar(20)    not null,
    captured_by     bigint         not null references app_user (id),
    confirmed_by    bigint         references app_user (id),
    cancel_reason   varchar(255),
    captured_at     timestamptz    not null default now(),
    updated_at      timestamptz    not null default now(),
    version         integer        not null default 0,
    constraint trade_ref_unique unique (trade_ref),
    constraint trade_external_ref_unique unique (external_ref),
    constraint trade_product_valid check (product in ('SPOT', 'FORWARD')),
    constraint trade_direction_valid check (direction in ('BUY', 'SELL')),
    constraint trade_status_valid check (status in
        ('CAPTURED', 'VALIDATED', 'CONFIRMED', 'SETTLED', 'CANCELLED')),
    constraint trade_notional_positive check (notional > 0),
    constraint trade_rate_positive check (rate > 0),
    constraint trade_value_date_not_before_trade_date check (value_date >= trade_date)
);

create index trade_status_idx on trade (status);
create index trade_value_date_idx on trade (value_date);
create index trade_counterparty_idx on trade (counterparty_id);
create index trade_pair_idx on trade (pair_id);

create table trade_event
(
    id          bigint generated by default as identity primary key,
    trade_id    bigint      not null references trade (id) on delete cascade,
    sequence_no integer     not null,
    event_type  varchar(20) not null,
    from_status varchar(20),
    to_status   varchar(20) not null,
    actor       varchar(120) not null,
    detail      varchar(500),
    occurred_at timestamptz not null default now(),
    constraint trade_event_sequence_unique unique (trade_id, sequence_no)
);

create index trade_event_trade_idx on trade_event (trade_id, sequence_no);

-- --- valuation -------------------------------------------------------------

create table trade_valuation
(
    id              bigint generated by default as identity primary key,
    trade_id        bigint          not null references trade (id) on delete cascade,
    valuation_date  date            not null,
    market_rate     numeric(18, 8)  not null,
    -- Undiscounted difference between the market rate and the traded rate.
    mtm_quote_ccy   numeric(20, 2)  not null,
    discount_factor numeric(18, 10) not null,
    -- The same figure discounted back from value date. This is the number that
    -- belongs in a P&L report.
    pv_quote_ccy    numeric(20, 2)  not null,
    created_at      timestamptz     not null default now(),
    constraint trade_valuation_unique unique (trade_id, valuation_date)
);

create index trade_valuation_date_idx on trade_valuation (valuation_date);
